spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://svc.sel3.cloudtype.app:30522/capstonedb
    username: root
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true	
openai:
  api-key: "sk-~ 꼴 형태의 api 키 넣는 곳임"
  model: "gpt-4o-mini"
  api-url: "https://api.openai.com/v1/chat/completions"