spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://svc.sel3.cloudtype.app:30522/capstonedb
    username: root
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true	
openai:
  api-url: "http://localhost:1234/v1/chat/completions" # 내 LM Studio 주소
  api-key: "not-needed" #LM Studio는 키를 검사하지 않지만, 빈칸이면 에러가 날 수 있으니 아무 글자나 넣기
  model: "my_recruiter_ai" #모델명